-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 00:35:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pro2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pro2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pro2` DEFAULT CHARACTER SET utf8 ;
USE `pro2` ;

-- -----------------------------------------------------
-- Table `pro2`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro2`.`carrera` (
  `idcarrera` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idcarrera`),
  UNIQUE INDEX `idcarrera_UNIQUE` (`idcarrera` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro2`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro2`.`estudiante` (
  `carnet` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `fechaNac` DATE NULL,
  `email` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `dpi` VARCHAR(20) NULL,
  `idcarrera` INT NOT NULL,
  `fechaCreacion` DATE NULL DEFAULT (curdate()),
  `creditosAprobados` INT NULL DEFAULT 0,
  PRIMARY KEY (`carnet`),
  INDEX `fk_estudiante_carrera_idx` (`idcarrera` ASC) VISIBLE,
  UNIQUE INDEX `carnet_UNIQUE` (`carnet` ASC) VISIBLE,
  CONSTRAINT `carrera`
    FOREIGN KEY (`idcarrera`)
    REFERENCES `pro2`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro2`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro2`.`docente` (
  `codigoSIIF` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `fechaNac` DATE NULL,
  `email` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `dpi` VARCHAR(20) NULL,
  `fechaRegistro` DATE NULL DEFAULT (curdate()),
  PRIMARY KEY (`codigoSIIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro2`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro2`.`curso` (
  `idcurso` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `creditosNecesarios` INT NULL,
  `creditosOtorga` INT NULL,
  `obligatorio` TINYINT NULL,
  `carrera_idcarrera` INT NOT NULL,
  PRIMARY KEY (`idcurso`),
  UNIQUE INDEX `idcurso_UNIQUE` (`idcurso` ASC) VISIBLE,
  INDEX `fk_curso_carrera1_idx` (`carrera_idcarrera` ASC) VISIBLE,
  CONSTRAINT `fk_curso_carrera1`
    FOREIGN KEY (`carrera_idcarrera`)
    REFERENCES `pro2`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro2`.`cursoHabilitado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro2`.`cursoHabilitado` (
  `idcursoHabilitado` INT NOT NULL AUTO_INCREMENT,
  `ciclo` VARCHAR(2) NULL,
  `cupoMaximo` INT NULL,
  `seccion` VARCHAR(45) NULL,
  `año` INT NULL,
  `curso_idcurso` INT NOT NULL,
  `docente_codigoSIIF` INT NOT NULL,
  `numAsignados` INT NULL DEFAULT 0,
  `numDesasignados` INT NULL DEFAULT 0,
  PRIMARY KEY (`idcursoHabilitado`, `curso_idcurso`),
  UNIQUE INDEX `idcursoHabilitado_UNIQUE` (`idcursoHabilitado` ASC) VISIBLE,
  INDEX `fk_cursoHabilitado_docente1_idx` (`docente_codigoSIIF` ASC) VISIBLE,
  INDEX `fk_cursoHabilitado_curso1_idx` (`curso_idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_cursoHabilitado_docente1`
    FOREIGN KEY (`docente_codigoSIIF`)
    REFERENCES `pro2`.`docente` (`codigoSIIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursoHabilitado_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `pro2`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro2`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro2`.`notas` (
  `idnotas` INT NOT NULL AUTO_INCREMENT,
  `curso_idcurso` INT NOT NULL,
  `ciclo` VARCHAR(45) NULL,
  `seccion` VARCHAR(45) NULL,
  `estudiante_carnet` INT NOT NULL,
  `nota` DECIMAL NULL,
  `año` INT NULL,
  PRIMARY KEY (`idnotas`),
  INDEX `fk_notas_estudiante1_idx` (`estudiante_carnet` ASC) VISIBLE,
  INDEX `fk_notas_curso1_idx` (`curso_idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_notas_estudiante1`
    FOREIGN KEY (`estudiante_carnet`)
    REFERENCES `pro2`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `pro2`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro2`.`acta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro2`.`acta` (
  `idacta` INT NOT NULL AUTO_INCREMENT,
  `ciclo` VARCHAR(45) NULL,
  `seccion` VARCHAR(45) NULL,
  `cursoHabilitado_idcursoHabilitado` INT NOT NULL,
  `cursoHabilitado_curso_idcurso` INT NOT NULL,
  `fechaHoraGeneracion` DATETIME NULL,
  PRIMARY KEY (`idacta`),
  INDEX `fk_acta_cursoHabilitado1_idx` (`cursoHabilitado_idcursoHabilitado` ASC, `cursoHabilitado_curso_idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_acta_cursoHabilitado1`
    FOREIGN KEY (`cursoHabilitado_idcursoHabilitado` , `cursoHabilitado_curso_idcurso`)
    REFERENCES `pro2`.`cursoHabilitado` (`idcursoHabilitado` , `curso_idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro2`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro2`.`asignacion` (
  `idasignacion` INT NOT NULL AUTO_INCREMENT,
  `estudiante_carnet` INT NOT NULL,
  `cursoHabilitado_idcursoHabilitado` INT NOT NULL,
  `cursoHabilitado_curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`idasignacion`),
  INDEX `fk_asignacion_estudiante1_idx` (`estudiante_carnet` ASC) VISIBLE,
  INDEX `fk_asignacion_cursoHabilitado1_idx` (`cursoHabilitado_idcursoHabilitado` ASC, `cursoHabilitado_curso_idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_asignacion_estudiante1`
    FOREIGN KEY (`estudiante_carnet`)
    REFERENCES `pro2`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacion_cursoHabilitado1`
    FOREIGN KEY (`cursoHabilitado_idcursoHabilitado` , `cursoHabilitado_curso_idcurso`)
    REFERENCES `pro2`.`cursoHabilitado` (`idcursoHabilitado` , `curso_idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro2`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro2`.`horario` (
  `cursoHabilitado_idcursoHabilitado` INT NOT NULL,
  `dia` INT NULL,
  `horario` VARCHAR(45) NULL,
  PRIMARY KEY (`cursoHabilitado_idcursoHabilitado`),
  INDEX `fk_table1_cursoHabilitado1_idx` (`cursoHabilitado_idcursoHabilitado` ASC) VISIBLE,
  CONSTRAINT `fk_table1_cursoHabilitado1`
    FOREIGN KEY (`cursoHabilitado_idcursoHabilitado`)
    REFERENCES `pro2`.`cursoHabilitado` (`idcursoHabilitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro2`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro2`.`historial` (
  `idhistorial` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `descripcion` VARCHAR(150) NULL,
  `tipo` VARCHAR(10) NULL,
  `historialcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idhistorial`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
